name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build env
      run: sudo apt-get install build-essential fakeroot devscripts haskell-debian-utils
    - name: Install build depends
      run: sudo apt install debhelper libglib2.0-dev libgtk2.0-dev libusb-1.0-0-dev libtool-bin libtool libjpeg-dev
    - name: debuild -tc
      run: debuild -tc
