name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build env
      run: apt-get install build-essential fakeroot devscripts haskell-debian-utils
    - name: Install build depends
      run: mk-build-deps --install debian/control
    - name: debuild -tc
      run: debuild -tc
